runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
- name: sendgrid
  version: 5.3.0
- name: gunicorn
  version: 19.7.1
